---
title: "Trabajo Opcional Edig"
author: "Mihai Cristian Mihalache Farcas y Rubén Tormo Piles"
date: "2025-11-10"
output: html_document
---


Librerías que hemos utilizado

```{r librerias, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(plm)       # L1, L2 [file:21]
library(forecast)  # L4, L5 [file:21]
library(tseries)   # opcional, tests TS
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
```

Datos, de donde los hemos sacado y que bases son.

```{r carga_perno}
perno <- read_excel(
  "pernoctaciones.xlsx",
  skip  = 8 ,        # salta filas de título; ajusta según veas
  n_max = 20
)

names(perno)[1] <- "ccaa"

perno_long <- perno %>%
  mutate(across(-ccaa, as.character)) %>%          # columnas de meses a char
  pivot_longer(
    cols = -ccaa,
    names_to  = "periodo",                         # ej. "2025M10"
    values_to = "pernoctaciones"
  ) %>%
  mutate(pernoctaciones = as.numeric(pernoctaciones)) %>%
  separate(periodo, into = c("anio", "mes"), sep = "M") %>%
  mutate(
    anio = as.integer(anio),
    mes  = as.integer(mes)
  ) %>%
  select(ccaa, anio, mes, pernoctaciones)
```

```{r carga_plazas}
plazas <- read_excel(
  "plazas.xlsx",
  skip  = 8 ,        # salta filas de título; ajusta según veas
  n_max = 20
)

# 1) Renombrar la primera columna
names(plazas)[1] <- "ccaa"

plazas_long <- plazas %>%
  mutate(across(-ccaa, as.character)) %>%          # columnas de meses a char
  pivot_longer(
    cols = -ccaa,
    names_to  = "periodo",                         # ej. "2025M10"
    values_to = "plazas"
  ) %>%
  mutate(plazas = as.numeric(plazas)) %>%
  separate(periodo, into = c("anio", "mes"), sep = "M") %>%
  mutate(
    anio = as.integer(anio),
    mes  = as.integer(mes)
  ) %>%
  select(ccaa, anio, mes, plazas)
```

```{r carga_ipi}
ipi <- read_excel(
  "IPI.xlsx",
  skip  = 8 ,        # salta filas de título; ajusta según veas
  n_max = 18
)

names(ipi)[1] <- "ccaa"

ipi_long <- ipi %>%
  mutate(across(-ccaa, as.character)) %>%          # columnas de meses a char
  pivot_longer(
    cols = -ccaa,
    names_to  = "periodo",                         # ej. "2025M10"
    values_to = "ipi"
  ) %>%
  mutate(ipi = as.numeric(ipi)) %>%
  separate(periodo, into = c("anio", "mes"), sep = "M") %>%
  mutate(
    anio = as.integer(anio),
    mes  = as.integer(mes)
  ) %>%
  select(ccaa, anio, mes, ipi)
```

```{r}
ipc <- read_excel(
  "ipc.xlsx",
  skip  = 8 ,        # salta filas de título; ajusta según veas
  n_max = 20
)

names(ipc)[1] <- "ccaa"
ipc$`2025M11` <- NULL

ipc_2010M01 = ipc$`2010M01`
```

```{r carga_adr}
adr <- read_excel(
  "ADR.xlsx",
  skip  = 7 ,        # salta filas de título; ajusta según veas
  n_max = 19
)

names(adr)[1] <- "ccaa"

# 1) Guardar la columna ccaa
ccaa <- adr[[1]]
# 2) Convertir meses a matriz numérica
adr_m <- as.matrix(adr[ , -1])
ipc_m <- as.matrix(ipc[ , -1])
adr_m <- apply(adr_m, 2, as.numeric)
ipc_m <- apply(ipc_m, 2, as.numeric)
# 3) Calcular ADR_real (elemento a elemento)
adr_real_m <- adr_m * ipc_2010M01 / ipc_m
# 4) Volver a data.frame y añadir ccaa
adr_real <- data.frame(ccaa = ccaa, adr_real_m, check.names = FALSE)


adr_real_long <- adr_real %>%
  mutate(across(-ccaa, as.character)) %>%          # columnas de meses a char
  pivot_longer(
    cols = -ccaa,
    names_to  = "periodo",                         # ej. "2025M10"
    values_to = "adr"
  ) %>%
  mutate(adr = as.numeric(adr)) %>%
  separate(periodo, into = c("anio", "mes"), sep = "M") %>%
  mutate(
    anio = as.integer(anio),
    mes  = as.integer(mes)
  ) %>%
  select(ccaa, anio, mes, adr)
```

```{r}
df <- perno_long |>
  left_join(plazas_long, by = c("ccaa", "anio", "mes")) |>
  left_join(adr_real_long,    by = c("ccaa", "anio", "mes")) |>
  left_join(ipi_long,    by = c("ccaa", "anio", "mes"))

df <- df |>
  mutate(
    # tiempo como año + fracción del año
    fecha_panel = anio + (mes - 1) / 12
  )

df_panel <- pdata.frame(df, index = c("ccaa", "fecha_panel"))

df_panel <- df_panel[
  complete.cases(df_panel[ , c("pernoctaciones", "adr", "plazas", "ipi")]),
]
```

```{r}
ggplot(df, aes(x = pernoctaciones)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  labs(title = "Histograma de Pernoctaciones", x = "Pernoctaciones", y = "Frecuencia")

ggplot(df, aes(x = adr)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  labs(title = "Histograma de ADR real", x = "ADR real", y = "Frecuencia")

ggplot(df, aes(x = plazas)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  labs(title = "Histograma de Plazas", x = "Plazas", y = "Frecuencia")

ggplot(df, aes(x = ipi)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  labs(title = "Histograma de IPI", x = "IPI", y = "Frecuencia")
```

```{r}
ggplot(df_plot, aes(x = adr, y = pernoctaciones)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", se = FALSE) +
  labs(x = "ADR real", y = "Pernoctaciones")

ggplot(df, aes(x = plazas, y = pernoctaciones)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", se = FALSE, color = "red") +
  labs(x = "Plazas", y = "Pernoctaciones")

ggplot(df, aes(x = ipi, y = pernoctaciones)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "loess", se = FALSE, color = "red") +
  labs(x = "IPI", y = "Pernoctaciones")
```

```{r anal_exploratorio}
summary(df_panel[ , c("pernoctaciones", "adr", "plazas", "ipi")])

cor(
  df_panel[ , c("pernoctaciones", "adr", "plazas", "ipi")],
  use = "complete.obs"
)

#-----------------------------------------------------------------------------------------------------------
# análisis multicolinealidad
vars_x <- df_panel[ , c("adr", "plazas", "ipi")]

cor(vars_x, use = "complete.obs")

library(car)
mod_pooled <- lm(pernoctaciones ~ adr + plazas + ipi, data = df_panel)
vif(mod_pooled)
# no hay multicolinealidad ya que no hay correlaciones significativas (máx. ≈ 0.64) y los VIF están por debajo de 2
#------------------------------------------------------------------------------------------------------------
```

```{r}
#modelo efectos fijos
modelo_ef <- plm(
  pernoctaciones ~ adr + plazas + ipi,
  data  = df_panel,
  model = "within"
)

summary(modelo_ef)
```

```{r}
#modelo de efectos fijos con variables dummies
df_panel$mes_factor <- as.factor(df_panel$mes)

modelo_ef_m <- plm(
  pernoctaciones ~ adr + plazas + ipi + mes_factor,
  data  = df_panel,
  model = "within"
)

summary(modelo_ef_m)
```

```{r}
#modelo efectos aleatorios con dummies
modelo_ea_m <- plm(
  pernoctaciones ~ adr + plazas + ipi + mes_factor,
  data  = df_panel,
  model = "random"
)
summary(modelo_ea_m)

#comparación de modelos
hausman_test <- phtest(modelo_ef_m, modelo_ea_m)
hausman_test
```
El test de Hausman (χ²(14)=277.73, p<0.001) rechaza la hipótesis nula de ausencia de correlación entre los efectos individuales y los regresores, por lo que el modelo de efectos fijos es el adecuado.

sexo sexual
